In [94]:
import pandas as pd
import numpy as np
import random

from sklearn.model_selection import train_test_split

# AITA dataset   2000/200 train/test  - TEENAGERS dataset 5000/500 train/test

In [4]:
# loading data
aita = pd.read_csv('data/aita.csv', index_col=0)


C:\Users\Patryk\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [56]:
teen = pd.read_csv('data/teens2.csv', index_col=0)

C:\Users\Patryk\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Patryk\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [5]:
aita = aita.loc[aita.score.notnull()]
aita = aita.loc[:, aita.columns!='url']

aita = aita.reset_index()
aita = aita.loc[:, aita.columns!='index']

In [57]:
teen = teen.loc[:, teen.columns!='Unnamed: 0.1']
teen = teen.loc[:, teen.columns!='url']
teen = teen.loc[teen.score.notnull()]
teen = teen.reset_index()
teen = teen.loc[:, teen.columns!='index']

In [117]:
aita

flair                                              title  \
0              asshole    aita for missing my shift at work and studying?   
1              asshole  aita for using robin williams' suicide to brea...   
2              asshole       aita for creating a fucked up love triangle?   
3       everyone sucks  aita refused to go in to see a movie after tic...   
4              asshole  aita for refusing to not touch my phone as the...   
...                ...                                                ...   
368616  not the a-hole  wibta if i contacted the wife of the man my mo...   
368617  not the a-hole              aita for going out with a friends ex?   
368618  not the a-hole  aita for not wanting to buy the makeup my mom ...   
368619         asshole  aita for telling my roommate [21f] that my fri...   
368620         asshole  aita for not going to a party that i wasn’t pe...   

                                                     text   score  \
0       i'm a highschool senior who works a part time ...    16.0   
1       on okcupid this girl listed only robin william...    13.0   
2       so it started last semester as i'm a third yea...    10.0   
3       now this happened a while ago and i'm pretty s...    29.0   
4       i figured out during a 7 hour road trip to go ...    10.0   
...                                                   ...     ...   
368616  this is going to be a loaded one.\n\nlong stor...  1781.0   
368617  they've broken up 4 months ago and i did try t...     0.0   
368618  so today we were at the mall, and went to the ...   131.0   
368619  my friend is a bisexual man who was previously...    15.0   
368620  so my friend had a party last night and i didn...   547.0   

        num_comments   created_utc is_self  num_crossposts  title_wc  \
0               17.0  1.422047e+09    True             NaN         9   
1               12.0  1.422843e+09    True             NaN        10   
2               16.0  1.423202e+09    True             NaN         8   
3               31.0  1.423225e+09    True             NaN        14   
4               30.0  1.423260e+09    True             NaN        18   
...              ...           ...     ...             ...       ...   
368616         290.0  1.575158e+09    True             NaN        23   
368617          13.0  1.575158e+09    True             NaN         8   
368618          32.0  1.575158e+09    True             NaN        11   
368619          40.0  1.575158e+09    True             NaN        12   
368620         142.0  1.575158e+09    True             NaN        13   

        selftext_wc  title_cc  selftext_cc  
0               120        47          614  
1                69        56          395  
2               306        44         1585  
3               415        65         2003  
4               177        99          952  
...             ...       ...          ...  
368616          459       114         2431  
368617           65        37          312  
368618          287        53         1417  
368619          336        64         1705  
368620          142        66          685  

[368621 rows x 12 columns]

In [84]:
aita.isna().sum()

flair                  0
title                  0
text                 186
score                  0
num_comments           0
created_utc            0
is_self                0
num_crossposts    347464
title_wc               0
selftext_wc            0
title_cc               0
selftext_cc            0
dtype: int64

In [88]:
teen.isna().sum()

flair                   0
title                   0
text              1238378
score                   0
num_comments            0
created_utc             0
is_self                 0
num_crossposts    4575085
title_wc                0
selftext_wc             0
title_cc                0
selftext_cc             0
dtype: int64

In [90]:
print(aita.columns)
print(teen.columns) # same columns

Index(['flair', 'title', 'text', 'score', 'num_comments', 'created_utc',
       'is_self', 'num_crossposts', 'title_wc', 'selftext_wc', 'title_cc',
       'selftext_cc'],
      dtype='object')
Index(['flair', 'title', 'text', 'score', 'num_comments', 'created_utc',
       'is_self', 'num_crossposts', 'title_wc', 'selftext_wc', 'title_cc',
       'selftext_cc'],
      dtype='object')


## Dividing datasets into train test with balanced classes - aita

In [138]:
random.seed(44)


class_count_in_train = 2000
class_count_in_test = 200

df = aita

df_train = pd.DataFrame(columns= df.columns)
df_test = pd.DataFrame(columns= df.columns)

unique_flairs = np.unique(df.flair, return_counts=True)


for i in range(len(unique_flairs[0])):
    flair_count = int(unique_flairs[1][i])
    flair = unique_flairs[0][i]
    print("flair number: " , i)
    
    df_cut = df[df.flair == flair]
    
    df_cut = df_cut.reset_index()
    df_cut = df_cut.loc[:, df_cut.columns!='index']
    
    if flair_count >= class_count_in_train + class_count_in_test:
        choices = np.random.choice(flair_count, class_count_in_train + class_count_in_test, replace=False)
        
        
        df_train_flair = df_cut.iloc[choices[0:class_count_in_train], :]
        df_test_flair = df_cut.iloc[choices[class_count_in_train:class_count_in_test + class_count_in_train], :]
        
        
        
        df_train =  pd.concat([df_train,df_train_flair], axis=0)
        df_test = pd.concat([df_test,df_test_flair], axis=0)

    else:
        choices = np.random.choice(flair_count, flair_count, replace=False)
        choices_test = choices[0:class_count_in_test]
        choices_train = np.random.choice(choices[class_count_in_test:(flair_count - 1)], class_count_in_train, replace=True)
        
        
        df_train_flair = df_cut.iloc[choices_train, :]
        df_test_flair = df_cut.iloc[choices_test, :]
        
        df_train = pd.concat([df_train,df_train_flair], axis=0)
        df_test = pd.concat([df_test,df_test_flair], axis=0)
        
        
        
# creating unbalanced train/test split

df = df.drop(list(set(df_train.index) | set(df_test.index)), axis=0)

X_train, X_test = train_test_split(df, test_size=0.1, random_state=44, shuffle = True)


df_train_unbalanced = pd.concat([df_train,X_train], axis=0)
df_test_unbalanced = pd.concat([df_test,X_test], axis=0)

flair number:  0
flair number:  1
flair number:  2
flair number:  3
flair number:  4
flair number:  5
flair number:  6
flair number:  7


In [139]:
df_train.to_csv("data/aita_train_balanced.csv")
df_test.to_csv("data/aita_test_balanced.csv")

df_train_unbalanced.to_csv("data/aita_train.csv")
df_test_unbalanced.to_csv("data/aita_test.csv")

In [51]:
np.unique(df_test.flair, return_counts=True)

(array(['asshole', 'everyone sucks', 'meta', 'no a-holes here',
        'not enough info', 'not the a-hole', 'tl;dr', 'update'],
       dtype=object),
 array([200, 200, 200, 200, 200, 200, 200, 200], dtype=int64))

In [53]:
np.unique(df_train.flair, return_counts=True)

(array(['asshole', 'everyone sucks', 'meta', 'no a-holes here',
        'not enough info', 'not the a-hole', 'tl;dr', 'update'],
       dtype=object),
 array([2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000], dtype=int64))

In [37]:
df_train_flair

flair                                              title  \
366   update  [update] wibta if i chose not to go to the leg...   
759   update  update: wibta if i took my roommate's cats as ...   
1544  update  update: aita for bringing my boyfriend to my s...   
636   update  update: aita for refusing to take care of my b...   
1616  update  update: wibta if i stopped baking cookies for ...   
...      ...                                                ...   
2847  update  [update] aita if i [20f] don’t split my inheri...   
1823  update  update: aita for having pot cookies out in the...   
2620  update  [update] aita for defending my daughter's name...   
1799  update  update from aita for ignoring my brother? peei...   
1810  update             update: aita for eating sexy potatoes?   

                                                   text    score  \
366   original post [here](https://www.reddit.com/r/...    199.0   
759                                           [removed]      1.0   
1544                                          [removed]      1.0   
636                                           [removed]      1.0   
1616  it’s been more than a year since my [original ...  37145.0   
...                                                 ...      ...   
2847                                          [removed]      1.0   
1823  link to the original post: https://old.reddit....   8546.0   
2620                                          [removed]      2.0   
1799                                          [removed]      1.0   
1810                                          [removed]      1.0   

      num_comments   created_utc is_self  num_crossposts  title_wc  \
366           22.0  1.581613e+09    True             NaN        16   
759            1.0  1.592064e+09    True             NaN        11   
1544           1.0  1.601077e+09    True             NaN        10   
636            1.0  1.590028e+09    True             NaN        11   
1616         622.0  1.601786e+09    True             NaN        16   
...            ...           ...     ...             ...       ...   
2847           1.0  1.620759e+09    True             NaN        12   
1823         282.0  1.604589e+09    True             NaN        14   
2620           1.0  1.616951e+09    True             NaN         8   
1799           1.0  1.604158e+09    True             NaN        10   
1810           1.0  1.604337e+09    True             NaN         6   

      selftext_wc  title_cc  selftext_cc  
366           352        85         2072  
759             1        53            9  
1544            1        61            9  
636             1        60            9  
1616          473        89         2604  
...           ...       ...          ...  
2847            1        71            9  
1823          368        67         2022  
2620            1        55            9  
1799            1        59            9  
1810            1        38            9  

[2000 rows x 12 columns]

## Dividing datasets into train test with balanced classes - teenagers

In [143]:
random.seed(44)

class_count_in_train = 100000 # 100k
class_count_in_test = 10000 # 10k

df = teen

df_train = pd.DataFrame(columns= df.columns)
df_test = pd.DataFrame(columns= df.columns)

unique_flairs = np.unique(df.flair, return_counts=True)


for i in range(len(unique_flairs[0])):
    flair_count = int(unique_flairs[1][i])
    flair = unique_flairs[0][i]
    print("flair number: " , i)
    
    df_cut = df[df.flair == flair]
    
    df_cut = df_cut.reset_index()
    df_cut = df_cut.loc[:, df_cut.columns!='index']
    
    if flair_count >= class_count_in_train + class_count_in_test:
        choices = np.random.choice(flair_count, class_count_in_train + class_count_in_test, replace=False)
        
        
        df_train_flair = df_cut.iloc[choices[0:class_count_in_train], :]
        df_test_flair = df_cut.iloc[choices[class_count_in_train:class_count_in_test + class_count_in_train], :]
        
        
        
        df_train =  pd.concat([df_train,df_train_flair], axis=0)
        df_test = pd.concat([df_test,df_test_flair], axis=0)

    else:
        choices = np.random.choice(flair_count, flair_count, replace=False)
        choices_test = choices[0:class_count_in_test]
        choices_train = np.random.choice(choices[class_count_in_test:(flair_count - 1)], class_count_in_train, replace=True)
        
        
        df_train_flair = df_cut.iloc[choices_train, :]
        df_test_flair = df_cut.iloc[choices_test, :]
        
        df_train = pd.concat([df_train,df_train_flair], axis=0)
        df_test = pd.concat([df_test,df_test_flair], axis=0)

        
        
# creating unbalanced train/test split

df = df.drop(list(set(df_train.index) | set(df_test.index)), axis=0)

X_train, X_test = train_test_split(df, test_size=0.1, random_state=44, shuffle = True)


df_train_unbalanced = pd.concat([df_train,X_train], axis=0)
df_test_unbalanced = pd.concat([df_test,X_test], axis=0)




flair number:  0
flair number:  1
flair number:  2
flair number:  3
flair number:  4
flair number:  5
flair number:  6
flair number:  7
flair number:  8
flair number:  9


In [144]:
df_train.to_csv("data/teen_train_balanced.csv")
df_test.to_csv("data/teen_test_balanced.csv")

df_train_unbalanced.to_csv("data/teen_train.csv")
df_test_unbalanced.to_csv("data/teen_test.csv")

In [70]:
np.unique(df_test.flair, return_counts=True)

(array(['advice', 'art', 'discussion', 'media', 'meme', 'other', 'rant',
        'relationship', 'serious', 'social'], dtype=object),
 array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
        10000], dtype=int64))

In [71]:
np.unique(df_train.flair, return_counts=True)

(array(['advice', 'art', 'discussion', 'media', 'meme', 'other', 'rant',
        'relationship', 'serious', 'social'], dtype=object),
 array([100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000,
        100000, 100000], dtype=int64))